### ISSUE TITLE
Running DRAWEXE test suite

### ISSUE THREAD

**Issue by teamblubee** [tpaviot/oce#678]
I'm on FreeBSD x86_64 12-Current and successfully compiling and installing this project. I want to do the test but I am having some issues.

FreeBSD first install the files into a staging directory which is just a clone of /usr/

I am running into issues because to run DRAWEXE you have to setup the env and env.sh in the scripts directory is suppose to do this.

From what I can tell ${CASROOT} is setup relative to where you run env.sh but since it's a stage directory then transfer to on FreeBSD ${PREFIX} usually /usr/local/...

What exactly is CASROOT and what needs to be setup to run the tests? What environmental variables? I've looked through the env.sh script a few times but I am still a bit unsure.
What do I need to put where to have the DRAWEXE properly function after setting up the env as in env.sh?

**Comment by teamblubee** [comment]
When I run DRAWEXE I get segfault, here's a gdb backtrace

```shell
(gdb) r
Starting program: /usr/local/bin/DRAWEXE 
(gdb) 
Program received signal SIGSEGV, Segmentation fault.
0x0000000807034d08 in vtable for __cxxabiv1::__si_class_type_info () from /lib/libcxxrt.so.1
(gdb) bt
#0  0x0000000807034d08 in vtable for __cxxabiv1::__si_class_type_info () from /lib/libcxxrt.so.1
#1  0x0000000805e1cd59 in __cxxabiv1::__dynamic_cast (src_ptr=0x8061238e0 <(anonymous namespace)::ctype_c>, 
    src_type=0x806117740 <typeinfo for std::locale::facet>, dst_type=0x806118818 <typeinfo for std::ctype<char>>, src2dst=src2dst@entry=0)
    at /usr/ports/lang/gcc6/work/gcc-6.4.0/libstdc++-v3/libsupc++/dyncast.cc:72
#2  0x0000000805ea1100 in std::has_facet<std::ctype<char> > (__loc=...)
---Type <return> to continue, or q <return> to quit---
   3/include/bits/locale_classes.tcc:110
#3  0x0000000805e949c4 in std::basic_ios<char, std::char_traits<char> >::_M_cache_locale (this=this@entry=0x8061225e8 <std::cout+8>, __loc=...) at /usr/ports/lang/gcc6/work/.build/x86_64-portbld-freebsd12.0/libstdc++-v3/include/bits/basic_ios.tcc:159
#4  0x0000000805e94b40 in std::basic_ios<char, std::char_traits<char> >::init (this=this@entry=0x8061225e8 <std::cout+8>, __sb=0x806121ec0 <__gnu_internal::buf_cout_sync>) at /usr/ports/lang/gcc6/work/.build/x86_64-portbld-freebsd12.0/libstdc++-v3/include/bits/basic_ios.tcc:132
#5  0x0000000805e31191 in std::basic_ostream<char, std::char_traits<char> >::basic_ostream (__sb=<optimized out>, this=<optimized out>, __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at /usr/ports/lang/gcc6/work/.build/x86_64-portbld-freebsd12.0/libstdc++-v3/include/ostream:85
#6  std::ios_base::Init::Init (this=<optimized out>) at /usr/ports/lang/gcc6/work/gcc-6.4.0/libstdc++-v3/src/c++98/ios_init.cc:91
#7  0x00000008040ea561 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /usr/local/lib/gcc6/include/c++/iostream:74
#8  0x00000008040ea594 in _GLOBAL__sub_I_FSD_BinaryFile.cxx(void) () at /usr/ports/cad/opencascadeCE/work/oce-0686232/src/FSD/FSD_BinaryFile.cxx:1208
#9  0x00000008006066ba in objlist_call_init (list=<optimized out>, lockstate=<optimized out>) at /usr/src/libexec/rtld-elf/rtld.c:2643
#10 0x00000008006059db in _rtld (sp=0x7fffffffe878, exit_proc=<optimized out>, objp=<optimized out>) at /usr/src/libexec/rtld-elf/rtld.c:759
#11 0x0000000800603669 in .rtld_start () at /usr/src/libexec/rtld-elf/amd64/rtld_start.S:39
#12 0x0000000000000000 in ?? ()
```

can I get some help sorting this out?
